dist: xenial
language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'
install:
  - pip install -r requirements.txt
  - pytest --version
  - mypy --version
script:
  - pytest
  - mypy --strict
    common.py
    entities/*.py
    dfn_configs.py
    generate*.py
    test_entities.py
    #test_common.py
    #test_generate_connectors.py
    #test_generate_qfn.py
  - flake8
  - isort --check-only
